method = "lightdp"
training-algorithm = "fedavg"
client-update-clip = 1.0
epsilon = 6.0
tag = "auto"
git-track-results = true
num-clients = 50
num-server-rounds = 8
max-colluders = 10
max-stragglers = 10
max-records-per-client = 0
partition-method = "iid"
dirichlet-alpha = 0.5
validation-fraction = 0.1
round-timeout = 300.0
